---
# tasks file for Bulk Host Registration
- name: Making directory to past the public key for the user "{{ username }}".
  file:
    path: '/"{{ username }}"/.ssh'
    state: directory

- name: Create empty file if the file does not exsist. 
  file:
    path: '/"{{ username }}"/.ssh/authorized_keys'
    state: touch

- name: Unregistering the system if it is registered anywhere else.
  redhat_subscription:
    state: absent 

- name: Cleaning the all packages in case if there are any old packages of katello-ca-consumer present.
  yum:
    name: katello-ca-consumer
    state: absent 

- name: Downloading the Katello-ca-consumer package from "{{ Satellite_Hostname }}" to register the system. 
  shell: 'rpm -Uvh http://"{{ Satellite_Hostname }}"/pub/katello-ca-consumer-latest.noarch.rpm --force'
  args:
    warn: false

- name: Register the Hosts to the "{{ Satellite_Hostname }}" using Activation Key.
  redhat_subscription:
    activationkey: "{{ Activation_Key }}"
    org_id: "{{ Organization_ID }}" 
    state: present

- name: Installing the Mandatory packages for the client system. 
  yum: 
    name: "{{ Packages }}"
  vars:
    Packages:
      - katello-host-tools
      - katello-host-tools-tracer
      - katello-agent

- name: Sharing the public key of foreman-proxy user  on the hosts.
  lineinfile:
    path: "/root/.ssh/authorized_keys"
    line: "{{ pubkey }}"
